### ISSUE TITLE
Update Rust client library for tapscript support

### ISSUE THREAD

**Issue by bigspider** [LedgerHQ/app-bitcoin-new#105]
When signing tapscript transactions, the SIGN_PSBT command returns `pubkey||tapleaf_hash` instead of just `pubkey`.
Cient library would be cleaner by replacing the older `pubkey` object  with a structured object that always contains a pubkey (33-bytes if non-taproot, 32 byte if taproot) and optionally the tapleaf_hash (for taproot scripts only).

This is a breaking change for the client library, so it needs to be respected with the semver versioning.

**Comment by iamhardikat11** [comment]
Hi, Can i take up this issue?

**Comment by bigspider** [comment]
Done in #139.
