### ISSUE TITLE
Ignore SLIP-132

### ISSUE THREAD

**Issue by 0xBEEFCAF3** [LedgerHQ/app-bitcoin-new#117]
I've noticed by testnet PSBTs are rejected if the extended pubkeys in the global map are not prefixed with `tpub`. 
Is there a reason why the prefix is being used for validation and not just the pubkey / path?

**Comment by bigspider** [comment]
The PSBT standard expects xpubs/tpubs, so I think rejecting non-standard prefixes is acceptable.

SLIP-132 can't be generalized to descriptors/wallet policies, so it should IMHO be considered deprecated.

**Comment by 0xBEEFCAF3** [comment]
Makes sense to me! Thanks Sal
Closing
