### ISSUE TITLE
Unable to sign PSBT with both segwit and non-segwit inputs

### ISSUE THREAD

**Issue by achow101** [LedgerHQ/app-bitcoin-new#16]
I am unable to sign a PSBT with a segwit wallet if it has both segwit and non-segwit inputs, and the non-segwit inputs do not include a witness_utxo. It appears that the function `sign_segwit` expects all inputs to have witness_utxos, but that is not the case if at least one of the inputs is non-segwit.

A solution to this issue is to include the witness_utxo for non-segwit inputs, but this goes against the PSBT spec. Furthermore, doing that means that it is not possible sign the PSBT with a legacy wallet as the signing function to use is determined by the presence of witness_utxo.

**Comment by bigspider** [comment]
Indeed, good catch. Will need to use the non_witness_utxo if the witness_utxo is not present to extract the prevout's value and scriptpubkey.
