### ISSUE TITLE
BIP44 uses 32bit int for coin type

### ISSUE THREAD

**Issue by ryan-shaw** [LedgerHQ/app-bitcoin-new#18]
Discovered trying to implement a coin with a coin type > 65535 causes coin type to overflow which in turns causes "Unusual derivation path". 

This app currently uses `unsigned short` for coin types, changing to `unsigned int` would support all BIP44 coin types such as the ones listed here - https://github.com/satoshilabs/slips/blob/master/slip-0044.md

For example, https://github.com/LedgerHQ/app-bitcoin-new/pull/6 coin type would overflow.

**Comment by bigspider** [comment]
Closing, only relevant for altcoins that will rather be handled in the [legacy bitcoin app repo](https://github.com/LedgerHQ/app-bitcoin).
