### ISSUE TITLE
nostr support

### ISSUE THREAD

**Issue by c0indev3l** [LedgerHQ/app-bitcoin-new#277]
Hello,

Is there any plan to support nostr (Notes and Other Stuff Transmitted by Relays) ?
https://www.reddit.com/r/ledgerwallet/comments/105kn64/nostr_app/

Kind regards

**Comment by bigspider** [comment]
Hi @c0indev3l, this repository is only for the Ledger Bitcoin app; a nostr app could be developed as a standalone project - see for example this prototype: https://github.com/b0l0k/ledgstr-app

There is no current plan to develop a nostr app internally.

**Comment by besoeasy** [comment]
@bigspider you added ledger sync app, maybe you can do nostr apps too, it would be killer feature
