### ISSUE TITLE
Is there a Rust example of createPaymentTransaction?

### ISSUE THREAD

**Issue by fancellu** [LedgerHQ/app-bitcoin-new#298]
i.e. https://github.com/LedgerHQ/app-bitcoin/blob/b7c6323ec5fdf96f5c69c306ae129a9261c09d6f/js/ledger-btc.js#L383

I've been looking for similar code in Rust, using bitcoin_client_rs (or anything else, I'm not fussy), but can't find anything.

I'm hoping that someone might have an idea

Thanks

**Comment by bigspider** [comment]
createPaymentTransaction is an old API that should be considered deprecated at this point. Modern wallets use the PSBT standard to work with transactions, and the idea is that you can bring your favorite library to create PSBTs (in Rust, the go-to library is definitely [rust-bitcoin](https://github.com/rust-bitcoin/rust-bitcoin)).

An advanced wallet wallet (using sophisticated scripts) that is integrated with Ledger is [liana](https://github.com/wizardsardine/liana), so maybe you might find some useful code there.
