### ISSUE TITLE
enable signing of coinstake transactions for peercoin

### ISSUE THREAD

**Issue by backpacker69** [LedgerHQ/app-bitcoin-new#32]
Current app does not allow peercoin coinstake transactions to be signed by ledger devices, this pull request solves it:
https://github.com/LedgerHQ/app-bitcoin-new/pull/30

I've tested it and it works for me for both testnet and mainnet peercoin chains.

**Comment by bigspider** [comment]
Closing; altcoins will be handled in the [legacy app repo](https://github.com/LedgerHQ/app-bitcoin) as commented in the pull request.
