### ISSUE TITLE
SIGHASH_DEFAULT is not recognized

### ISSUE THREAD

**Issue by achow101** [LedgerHQ/app-bitcoin-new#47]
If a PSBT has inputs with the sighash type field populated, taproot inputs that have SIGHASH_DEFAULT set are rejected with `Only SIGHASH_ALL is currently supported`. However SIGHASH_DEFAULT is the same as SIGHASH_ALL so this should not be rejected.

**Comment by bigspider** [comment]
Good point. We were already looking into this matter for issue #40, as SIGHASH_DEFAULT should produce 64-byte signatures on taproot and save 1 byte; we'll make sure to add support in the next release.

**Comment by bigspider** [comment]
Solved in #56.
