### ISSUE TITLE
Add explicit warning for transactions with too high fees

### ISSUE THREAD

**Issue by bigspider** [LedgerHQ/app-bitcoin-new#58]
It would be useful to have a warning if the amount paid to fees is large compared to the total amount spent in the inputs, in order to make certain user mistakes much less likely.

**Comment by rxbryan** [comment]
Hello, I want to work on this issue. Can I get assigned.

**Comment by bigspider** [comment]
Hello @rxbryan, thanks for your interest in contributing!

While the issue itself is probably not technically difficult, it might require some thinking to come up with good specs. For examples, here are some questions to address before writing any code (I've not yet thought of good answers):

- When would the warning be shown? A possible answer: if the fees are larger than some predefined X% of the total (What's a good X?). Do we show the warning regardless of the total transaction value, or only if it's above some predefined absolute amount? If so, what's a good threshold?
- Should the warning be shown if there are external inputs (that is, inputs not controlled by the wallet)? If so, does anything change in that case for the decisions above? (note that there is already a separate warning about the external inputs, in that case).

Since this is a user-facing issue, it might be wiser to validate the specs with Ledger's product and design teams before implementing them.

Probably not really a "good first issue" − removing the label.

**Comment by rxbryan** [comment]
hey @bigspider, regarding the question and your suggested possible answers.
 
> * When would the warning be shown? A possible answer: if the fees are larger than some predefined X% of the total (What's a good X?).  

I think using sats per byte would be a better metric for calculating fees. 

>Do we show the warning regardless of the total transaction value, or only if it's above some predefined absolute amount? If so, what's a good threshold?

At this time a fee of about 60-70 sats per byte would guarantee a transaction would be included in the next block. We could use this as our base and only show the warning when the fee goes substantially above it (eg about 1.5 - 2x).

> * Should the warning be shown if there are external inputs (that is, inputs not controlled by the wallet)? If so, does anything change in that case for the decisions above? (note that there is already a separate warning about the external inputs, in that case).

As long as there are inputs controlled by the wallet, we should show a warning.

> Since this is a user-facing issue, it might be wiser to validate the specs with Ledger's product and design teams before implementing them.

I don't know how to go about doing that!
In this case I should probably choose some other issue while I get more familiar with the ecosystem.

**Comment by bigspider** [comment]
You're confusing between the feerate (chosen by the software wallet based on the fee estimators / mempool congestion / etc.), and the actual transaction fee, which is an absolute amount of coins that the user can inspect on the hardware device before signing the transaction.
Only the transaction fee is the concern of the device.
